name: API Automation - Newman + Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman & Allure
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure
          npm install -g allure-commandline

      - name: Run Smoke Collection
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          newman run collections/ReqRes_Smoke.postman_collection.json \
            -e environments/QA.postman_environment.json \
            --env-var "base_url=${BASE_URL}" \
            --env-var "api_key=${API_KEY}" \
            -r cli,allure \
            --reporter-allure-export allure-results-smoke

      - name: Generate Smoke Allure Report
        run: |
          allure generate allure-results-smoke --clean -o allure-report-smoke

      - name: Upload Smoke Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-smoke
          path: allure-report-smoke

  regression-tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    needs: smoke-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman & Allure
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure
          npm install -g allure-commandline

      - name: Run Regression Collection
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          newman run collections/ReqRes_Regression.postman_collection.json \
            -e environments/QA.postman_environment.json \
            --env-var "base_url=${BASE_URL}" \
            --env-var "api_key=${API_KEY}" \
            -r cli,allure \
            --reporter-allure-export allure-results-regression

      - name: Generate Regression Allure Report
        run: |
          allure generate allure-results-regression --clean -o allure-report-regression

      - name: Upload Regression Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-regression
          path: allure-report-regression
